### ISSUE TITLE
Improve Code Coverage

### ISSUE THREAD

**Issue by ryanmrichard** [CMakePP/CMakeDoc#9]
Code coverage should be as close to 100% as possible before the 1.0 alpha release.

**Comment by AutonomicPerfectionist** [comment]
I believe I have found the problem as to why Github's coverage is reporting significantly lower than a local coverage report. TravisCI is not configured to install Antlr4 and so any tests requiring it, which are most, don't even run. They aren't marked as failing because they error on initial loading and not during the test invocation.

**Comment by ryanmrichard** [comment]
Awesome find. It'd be good to figure out how to get the current state to be reported as failed tests since not having a dependency should crash the program. Honestly, I would have expected Python to return an error code in this case to begin with.

**Comment by ryanmrichard** [comment]
Fixed with #19
